" Global settings
set hidden                                                                                                              " don't unload buffer when switching away
set modeline                                                                                                            " allow per-file settings via modeline
set exrc                                                                                                                " enable per-directory .vimrc files
set secure                                                                                                              " disable unsafe commands in local .vimrc files
set encoding=utf-8 fileencoding=utf-8 termencoding=utf-8                                                                " saving and encoding
set nobackup nowritebackup noswapfile autoread                                                                          " no backup or swap
set hlsearch incsearch ignorecase smartcase                                                                             " search
set wildmenu                                                                                                            " completion
set backspace=indent,eol,start                                                                                          " sane backspace
set clipboard=unnamed                                                                                                   " use the system clipboard for yank/put/delete
set mouse=a                                                                                                             " enable mouse for all modes settings
set nomousehide                                                                                                         " don't hide the mouse cursor while typing
set mousemodel=popup                                                                                                    " right-click pops up context menu
set ruler                                                                                                               " show cursor position in status bar
set relativenumber                                                                                                      " show relative line numbers
set number                                                                                                              " show absolute line number of the current line
set nofoldenable                                                                                                        " I fucking hate code folding
set scrolloff=10                                                                                                        " scroll the window so we can always see 10 lines around the cursor
set textwidth=80                                                                                                        " show a vertical line at the 79th character
set cursorline                                                                                                          " highlight the current line
set printoptions=paper:letter                                                                                           " use letter as the print output format
set laststatus=2                                                                                                        " always show status bar
set nocompatible                                                                                                        " stops vim from behaving in a strongly vi
set nowrap                                                                                                              " no wrap line
set visualbell                                                                                                          " don't beep
set noerrorbells                                                                                                        " don't beep

" Formatting
filetype plugin indent on
set shiftwidth=2 tabstop=2 softtabstop=2 expandtab autoindent

" Appearance
syntax on
set background=dark
set colorcolumn=120
set t_Co=256

" Custom theme
highlight clear
" syntax reset

set list
set listchars=tab:»\ ,trail:·,extends:»,precedes:«,eol:¬

let &colorcolumn="121,".join(range(121,999),",")                                                                        " Background after vertical line.

highlight ColorColumn  ctermbg=235 ctermfg=245 cterm=NONE
highlight CursorLine   ctermbg=240 ctermfg=255 cterm=NONE
highlight CursorLineNr ctermbg=240             cterm=NONE
highlight LineNr       ctermbg=235 ctermfg=250 cterm=NONE
highlight SpecialKey   ctermbg=0   ctermfg=255 cterm=NONE
highlight NonText      ctermbg=0   ctermfg=236 cterm=NONE

" Status line
highlight User1 ctermfg=0   ctermbg=214 cterm=NONE
highlight User2 ctermfg=0   ctermbg=214 cterm=NONE
highlight User3 ctermfg=0   ctermbg=214 cterm=NONE

set statusline=
set statusline+=%1*                                                                                                     " Switch to colour User1
set statusline+=[%n]                                                                                                    " Buffer number
set statusline+=%2*                                                                                                     " Set color
set statusline+=%f                                                                                                      " Path to the file
set statusline+=%y                                                                                                      " File Type
set statusline+=[%{''.(&fenc!=''?&fenc:&enc).''}                                                                        " Encoding
set statusline+=\|                                                                                                      " Separator
set statusline+=%{&ff}]                                                                                                 " FileFormat (dos/unix..)
set statusline+=%=                                                                                                      " Switch to the right side
set statusline+=%8*\ L:                                                                                                 " Separator
set statusline+=%l                                                                                                      " Current line
set statusline+=/                                                                                                       " Separator
set statusline+=%L                                                                                                      " Total lines
set statusline+=%9*\ C:%03c\                                                                                            " Current column
set statusline+=%{GitBranch()}

" Trim whitespace
nnoremap <Leader>rtw :%s/\s\+$//e<CR>
function! TrimWhiteSpace()
  %s/\s\+$//e
endfunction
nnoremap <silent> <Leader>rts :call TrimWhiteSpace()<CR>
autocmd FileWritePre    * :call TrimWhiteSpace()
autocmd FileAppendPre   * :call TrimWhiteSpace()
autocmd FilterWritePre  * :call TrimWhiteSpace()
autocmd BufWritePre     * :call TrimWhiteSpace()

" Git
function! GitBranch()
  return system("git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/\(.*\)/(\1)/'")
endfunction



" Key map
let mapleader = ","
let maplocalleader = ","
