#!/bin/bash

URL=$1
FILE=$2

/usr/bin/curl -H "Content-Type: application/json" \
              -XGET $URL \
              --silent \
              --data @$FILE \
              | \
              /usr/bin/python -mjson.tool
